#!/bin/bash
# If you prefer a zsh keybinding check:
# https://github.com/gessen/zsh-fzf-kill/blob/master/fzf-kill.plugin.zsh

FZF_DEFAULT_OPTS="--min-height=100 --prompt 'pkill -9 '"
if [[ "${UID}" != "0" ]]; then
  pid=$(ps -f -u ${UID} | awk '{print $8}' | sed 1d | sort | uniq | xargs -l basename | fzf -m)
else
  pid=$(ps -ef | awk '{print $8}' | sed 1d | sort | uniq | xargs -l basename | fzf -m)
fi

if [[ "x$pid" != "x" ]]; then
  echo $pid | xargs pkill "-${1:-9}"
fi
