#!/bin/bash
# If you prefer a zsh keybinding check:
# https://github.com/gessen/zsh-fzf-kill/blob/master/fzf-kill.plugin.zsh

FZF_DEFAULT_OPTS="--min-height=100 --prompt 'kill -9 '"
COLS_2_AND_8='{for(i=1;i<=NF;i++) if(i!=1 && i!=3 && i!=4 && i!=5 && i!=6 && i!=7) printf "%s ", $i; print ""}'


# TODOS
# ========================================
# TODO: Align fzf to make it beautiful
# TODO: USE "ps -p 802080 -o comm=" to extract the program name, 
# instead of showing the full command (because we don't wanna list subprocesses)
#
# CODE
# ========================================
# List all user processes, extract the columns 2 and 8, delete the first line
# order, eliminate repeated entries, send to fzf, and extract the first column
# of the selectec entry.
if [[ "${UID}" != "0" ]]; then
  pid=$(ps -f -u ${UID} | awk "$COLS_2_AND_8" | sed 1d | sort | uniq | fzf -m | awk '{print $1}')
else
  pid=$(ps -ef | awk "$COLS_2_AND_8" | sed 1d | sort | uniq | fzf -m | awk '{print $1}')
fi

if [[ "x$pid" != "x" ]]; then
  # Kill the parent process
  ps -o ppid $pid | sed 1d | xargs kill "-${1:-9}"
fi
